### ISSUE TITLE
무한스크롤 관련 버그를 해결한다

### ISSUE THREAD

**Issue by 1119wj** [boostcampwm-2024/web09-DailyRoad#124]
### 🐞 Describe

- 페이지가 5를 넘어간 뒤로는 같은 페이지를 요청보내는 현상
- 데이터가 있음에도 스크롤시 요청을 안 보낼 때가 있음 '서울' 키워드 검색
- 장소를 선택 안해도 장소추가하기 버튼이 클릭되고 페이지가 전환될 수 있음

### 🌏 Environment

.

**Comment by Miensoap** [comment]
이거 해결됬나요?
