### ISSUE TITLE
검색 키워드에 캐싱을 적용한다

### ISSUE THREAD

**Issue by koomchang** [boostcampwm-2024/web09-DailyRoad#161]
### ✨ Describe

서비스 특성상 같은 키워드 검색이 많지 않을 것이고 ,

여러 사용자가  같은 키워드를 검색할 경우가 적다고 판단

→ 브라우저 캐싱 사용 , 메모리 캐시 당장 적용 x + ES 캐시만 적용

### ✅ Tasks

- [ ] 브라우저 캐싱 설정
- [ ] ES 캐시 적용

### 🕰️ Estimated Time of Completion

6

**Comment by Miensoap** [comment]
클라이언트에서 동일 검색어시 검색 버튼 비활성화로 해결하기로 논의
