### ISSUE TITLE
줌 레벨에 따른 지도 클러스터링 기능을 구현한다

### ISSUE THREAD

**Issue by koomchang** [boostcampwm-2024/web09-DailyRoad#171]
### ✨ Describe

줌 레벨에 따른 지도 클러스터링 기능을 구현한다.

- 줌 레벨에 따라 지역을 어떻게 나눌지 정해야 할 것 같음

### ✅ Tasks

줌 레벨에 따른 지도 클러스터링 기능을 구현

### 🕰️ Estimated Time of Completion

36

**Comment by Miensoap** [comment]
구글 API 사용하기로 논의
