### ISSUE TITLE
실제 데이터 확보를 위한 구글 Maps 크롤링을 한다

### ISSUE THREAD

**Issue by koomchang** [boostcampwm-2024/web09-DailyRoad#172]
### ✨ Describe

실제 데이터 확보를 위한 구글 Maps 크롤링을 한다

### ✅ Tasks

- 24시간 동작할 수 있는 크롤링 스크립트 작성
- 수집/가공/저장 파이프라인 구성

### 🕰️ Estimated Time of Completion

36

**Comment by Miensoap** [comment]
![image](https://github.com/user-attachments/assets/5c25e741-b276-41f6-81b0-53e11bb44e25)
![image](https://github.com/user-attachments/assets/37f7eff5-57a2-4ed6-95be-a13d4735875e)

`chrome` + `selenium` + `python` 이용해 수집/가공 동시에 진행중

**Comment by Miensoap** [comment]
카테고리가 모두 명소로 매핑되는 현상?

**Comment by koomchang** [comment]
> * 카테고리가 모두 명소로 매핑되는 현상?
> * `google_place_id` 정보가 없음 ->  DB에 추가할 때 상호명 + 주소 로 중복 처리
>   
>   * 하면 오래걸릴까요?

DB 추가 전에 필터링 하고 넣는게 더 빠르지 않을가 합니다!

**Comment by Miensoap** [comment]
> DB 추가 전에 필터링 하고 넣는게 더 빠르지 않을가 합니다!

DB랑 비교해서 필터링해야 하지 않을까요
