### ISSUE TITLE
API 명세서를 작성한다

### ISSUE THREAD

**Issue by koomchang** [boostcampwm-2024/web09-DailyRoad#22]
### ✨ Describe

초기 API 명세서를 작성하고 구현과 병행하며 차주 명세서를 함께 작성한다

### ✅ Tasks

- [ ] API 명세서 작성

### 🕰️ Estimated Time of Completion

1주

**Comment by Miensoap** [comment]
https://elastic-bread-9ef.notion.site/API-12963e6f4ee98039bc6adbbbba21bb40
