### ISSUE TITLE
Commit message에 이슈 번호가 추가되는 것을 자동화한다

### ISSUE THREAD

**Issue by koomchang** [boostcampwm-2024/web09-DailyRoad#41]
### ✨ Describe

> Commit message에 이슈 번호가 추가되는 것을 자동화한다
- slack에서 J230 정지호 님의 공유 글을 보며 적용하면 편할 것 같다고 생각했습니다.
[commit message에 이슈 번호 추가 자동화 하기](https://github.com/boostcampwm-2024/web14-betting-duck/wiki/commit-message%EC%97%90-%EC%9D%B4%EC%8A%88-%EB%B2%88%ED%98%B8-%EC%B6%94%EA%B0%80-%EC%9E%90%EB%8F%99%ED%99%94-%ED%95%98%EA%B8%B0)

### ✅ Tasks

- `.git/hooks/prepare-commit-msg` 파일 생성

### 🕰️ Estimated Time of Completion

1

### 🙋🏻 More

`.git/hooks/prepare-commit-msg` 에다가 아래 파일을 작성해주세요

```sh
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

ISSUE_ID=$(echo "$BRANCH_NAME" | grep -oE '#[0-9]+')

if [ -n "$ISSUE_ID" ]; then
    sed -i.bak -e "1s/$/ $ISSUE_ID/" "$1"
fi
```

이후 권한을 부여해줍니다.
`chmod +x .git/hooks/prepare-commit-msg`
이후 커밋을 하면 뒤에 자동으로 이슈번호가 붙습니다.
ex)
> 내가 작성한 커밋메세지
> `feature: 어떤 기능 구현`

> 반영되는 커밋메세지
> `feature: 어떤 기능 구현 #이슈번호`

**Comment by koomchang** [comment]
https://the-dailyroad.slack.com/archives/C08016MUQKA/p1730782927659699

확인하시고 반영해주세요. 모두 반영하면 `issue` 닫겠습니다!

**Comment by Miensoap** [comment]
![image_720](https://github.com/user-attachments/assets/327b5bb7-0292-4f99-bbe3-1c769cb45ef8)
![image_480](https://github.com/user-attachments/assets/1d0f3000-06d1-4fa6-ad3f-8e70c6eb1034)
![image_360](https://github.com/user-attachments/assets/c44c7a14-8367-4665-a2a7-7661b70ff366)

ㅜㅜ

**Comment by Miensoap** [comment]
ㅜㅜ

![image_720](https://github.com/user-attachments/assets/79d6fa8e-2018-40c4-80c9-b71115077654)
![image_480](https://github.com/user-attachments/assets/cb4f106a-e203-4992-a4dd-21e32747aea0)
![image_360](https://github.com/user-attachments/assets/48f0debe-9d09-439a-a5eb-edaaa03d0b81)
