### ISSUE TITLE
Test 환경을 구성한다

### ISSUE THREAD

**Issue by koomchang** [boostcampwm-2024/web09-DailyRoad#66]
### ✨ Describe

- `src` 내부의 `spec.ts`가 아닌 `test` 내부 `test.ts` 를 이용하기 위한 설정
- 테스트용 DB를 Docker 컨테이너로 생성
- GitHub Actions에서도 테스트용 DB를 만들어서 테스트 가능하도록 workflow 설정

### ✅ Tasks

- [x] test 디렉토리 `*.test.ts` 를 이용하기 위한 설정
- [x] 테스트용 DB를 위한 설정

### 🕰️ Estimated Time of Completion

4

**Comment by Miensoap** [comment]
Q. test 디렉토리 내에 두는데 .test postfix 붙일 필요 있을까요?

**Comment by koomchang** [comment]
> Q. test 디렉토리 내에 두는데 .test postfix 붙일 필요 있을까요?

테스트 디렉토리 내부에서 `test` 설정을 위한 파일들도 있기 때문에 `.test` 가 있으면 정말 테스트를 위한 파일들을 구분할 수 있을 것 같아요!

**Comment by Miensoap** [comment]
오.. 동의합니다
